### ISSUE TITLE
What3word reverse function not loading Mongolian text

### ISSUE THREAD

**Issue by devsteppe9** [what3words/w3w-javascript-wrapper#6]
**This is my code**
const options = {
        key: '*********',
        language: 'mn'
    };
    const w3w = new W3W.Geocoder(options);
const _this = this;
    const callback = {
      onSuccess: function(data) {
        console.log(data);
        _this.customerAddress.w3wAddress = data.words;
      },
      onFailure: function(data) {
          console.log(JSON.stringify(data));
      }
    };
const params = {
      coords: [this.customerAddress.longitude, this.customerAddress.latitude],
      lang: 'mn',
      format: 'json'
    };
    w3w.reverse(params, callback);

**Comment by devsteppe9** [comment]
**And there is i am receiving English 3words not Mongolian**
![capture](https://user-images.githubusercontent.com/18748558/39424506-a5800766-4ca9-11e8-81ef-69573bc0e017.PNG)

**Comment by devsteppe9** [comment]
Can you review this bug sir

**Comment by tsamaya** [comment]
Hi,
first the language parameter on the constructor is `lang` like in the API requests.
The ouput language is `mn` so the API returned the right language. 
The words are in english even if you asked for Mongolian because we covered only landmass with non english language. We also excluded glacier, that's why your example in Antartica returns an address with english words.
I hope this helped.
All the best

**Comment by devsteppe9** [comment]
Thank you for your response,
I'am followed your instructions but I don't received Mongolian three words there are only English words.
So is this possible to receive Mongolian three words. If possible how? Can you give me possible case examples?
